const ACTIONS = {
  SET_FILTERS: 'SET_FILTERS',
  SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
  GET_GENERS_BY_TYPE: 'GET_GENERS_BY_TYPE',
  GET_MEDIA_ITEMS: 'GET_MEDIA_ITEMS',
  SET_CATEGORY: 'SET_CATEGORY',
};

export default ACTIONS;
